services:
  agi-countdown:
    build: .
    container_name: agi-countdown
    ports:
      - '45500:3000'
    volumes:
      - /volume1/Hideout-Server/data/apps/agi-countdown:/app
      - /app/node_modules
    restart: unless-stopped